syntax on
set noerrorbells
set noswapfile
set smartindent
set nowrap
set smartcase
set laststatus=2
set number
set backspace=indent,eol,start
set softtabstop=4
set tabstop=4
set shiftwidth=4
set expandtab
