add_newline = false

# ~/.config/starship.toml
[character]
success_symbol="[](bold green)"
error_symbol="[](bold red)"

[golang]
symbol = "󰟓 "

[python]
symbol = " "
python_binary = "python3"

[rust]
symbol = " "
detect_extensions = ["rs"]
detect_files = ["Cargo.toml"]

[lua]
symbol = "󰢱 "
detect_extensions = ["lua", "nse"]
