[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Alabaster.dark.toml"
]

[cursor.style]
shape = "underline"

[env]
TERM = "alacritty"

[font]
size = 16

  [font.bold]
  family = "Mononoki Nerd Font"
  style = "Bold"

  [font.normal]
  family = "Mononoki Nerd Font"
  style = "Regular"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.8

  [window.dimensions]
  columns = 80
  lines = 30

  [window.padding]
  x = 5
  y = 5
