;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282934
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880
red = #ee0000
green = #00ff00
magenta = #d7005f
blue = #0087ff
purple = #af00ff
orange = #d78700
yellow = #ffff00
peach = #ff875f

[bar/mainbar]
width = 100%
height = 24pt
; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #282934

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = mononoki Nerdfont:size=10;2
font-1 = Font Awesome 6 Free-Regular-4
font-2 = Font Awesome 6 Free-Solid-900
font-3 = Font Awesome 6 Brands-Regular

modules-left = xworkspaces xwindow
modules-right = cpu memory temperature filesystem eth pulseaudio date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.purple}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = disk   (%percentage_used%%)
label-mounted-foreground = ${colors.purple}
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume = "  VOL (<label-volume>)"
format-volume-foreground = ${colors.peach}
label-volume = %percentage%%

label-muted = 
label-muted-foreground = ${colors.disabled}
click-right = pavucontrol

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format = " RAM (<label>)"
format-foreground = ${colors.magenta}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format = "  CPU (<label>)"
format-foreground = ${colors.yellow}
label = %percentage:2%%

[module/temperature]
type = internal/temperature
interval = 0.5
base-temperature = 20
thermal-zone = 0
format = " TEMP (<label>)"
format-foreground = ${colors.orange}
label = "%temperature-c%"

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#0087ff}  Ethernet (%local_ip%)

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label =   %date%
label-foreground = ${colors.green}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
